#!/bin/sh
# Xsetup - run as root before the login dialog appears
if xrandr | grep "HDMI-1 connected"; then
    xrandr --output eDP-1 --mode 1920x1200 --pos 0x1080 --rotate normal \
           --output HDMI-1 --primary --mode 1920x1200 --pos 0x0 --rotate normal \
           --output HDMI-2 --off
elif xrandr | grep "^DP-1 connected"; then
    xrandr --output eDP-1 --mode 1920x1200 --pos 0x1080 --rotate normal \
           --output DP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal \
           --output HDMI-2 --off
else
    xrandr --output eDP-1 --primary --mode 1920x1200 --pos 0x0 --rotate normal \
           --output HDMI-1 --off \
           --output DP-1 --off \
           --output HDMI-2 --off
fi

