preload = /home/jnyaga/Pictures/wallpapers/background-10.jpg
wallpaper = HDMI-A-1, /home/jnyaga/Pictures/wallpapers/background-10.jpg
wallpaper = eDP-1, /home/jnyaga/Pictures/wallpapers/background-10.jpg
